name: Create and publish a Docker image

on:
  push:
    branches:
      - main

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USER: druzai
      DOCKERHUB_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      DOCKERHUB_REPOSITORY: druzai/vkbotdiary

    steps:
      - uses: actions/checkout@v2

      - name: Get commit tag
        id: commit
        run: |
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

      - name: Docker login
        run: |
          docker login -u $DOCKERHUB_USER -p $DOCKERHUB_ACCESS_TOKEN

      - name: Docker build
        env:
          SOURCE_TAG: ${{ steps.commit.outputs.SOURCE_TAG }}
        run: |
          docker build -t $DOCKERHUB_REPOSITORY .
          docker tag $DOCKERHUB_REPOSITORY:latest $DOCKERHUB_REPOSITORY:$SOURCE_TAG

      - name: Docker push
        run: |
          docker push $DOCKERHUB_REPOSITORY:$SOURCE_TAG
          docker push $DOCKERHUB_REPOSITORY:latest
