name: Build with pyinstaller and release

on:
  push:
    branches:
      - main

jobs:
  create_release:
    name: Create release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Get commit tag
        id: commit
        run: \.github\workflows\read_version.sh

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ steps.commit.outputs.SOURCE_TAG }}
          release_name: ${{ steps.commit.outputs.SOURCE_TAG }}
          draft: false
          prerelease: false

  release_built_assets:
    name: Release built assets
    needs: create_release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [ 3.8 ]
        os: [ ubuntu-latest, windows-latest ]
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Get commit tag
        id: commit
        run: \.github\workflows\read_version.sh

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 pyinstaller==4.0
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Build with pyinstaller
        run: |
          make

      - name: Upload release asset with *nix
        if: matrix.os != 'windows-latest'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./build_dist/VkBotDiary
          asset_name: VkBotDiary_linux_x64_py_${{ matrix.python-version }}_${{ steps.commit.outputs.SOURCE_TAG }}
          asset_content_type: application/x-executable

      - name: Upload release asset with windows
        if: matrix.os == 'windows-latest'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./build_dist/VkBotDiary.exe
          asset_name: VkBotDiary_windows_x64_py_${{ matrix.python-version }}_${{ steps.commit.outputs.SOURCE_TAG }}.exe
          asset_content_type: application/vnd.microsoft.portable-executable

